allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - react-hotkeys-hook@5.3.3
  - '@types/chrome@0.2.5'
onlyBuiltDependencies:
  - puppeteer
  - unrs-resolver
peerDependencyRules:
  allowedVersions:
    "@doist/typist@15>react": "19"
    "@doist/typist@15>react-dom": "19"
